# ==============================================
# MPV Configuration
# ==============================================

#### General
profile=gpu-hq
vo=gpu-next
hwdec=auto-safe
keep-open=yes
cursor-autohide-fs-only=yes
cursor-autohide=300
volume=100
volume-max=200
osd-bar=no
fullscreen=yes
save-position-on-quit=yes

#### Shaders
# If lag occurs change to bicubic_fast.
scale=spline36
dscale=mitchell
cscale=spline36

#### Screenshots
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-directory=~/Pictures/Screenshots/

#### Subtitle Options
demuxer-mkv-subtitle-preroll=yes  # Try harder to show embedded soft subtitles when seeking somewhere.
sub-fix-timing=no                 # Adjust subtitle timing to remove minor gaps or overlaps between subtitles.
sub-auto=fuzzy                    # Load all subs containing the media filename.

#### Deband (Disabled by default)
deband=no
deband-iterations=2
deband-threshold=35
deband-range=20
deband-grain=5
